[package]
name = "halo2wrong"
version = "0.1.0"
authors = ["kilic <kiliconu@itu.edu.tr>"]
edition = "2021"

[dependencies]
cfg-if = "0.1"

[dependencies.halo2_zcash]
package = "halo2_proofs"
git = "https://github.com/zcash/halo2.git"
version = "0.1.0-beta.2"
optional = true

[dependencies.halo2_kzg]
package = "halo2_proofs"
git = "https://github.com/appliedzkp/halo2.git"
rev = "9d3ab0cf7be57a828df6cedb8f58476b483fdde1"
optional = true

[features]
default = ["zcash"]
zcash = ["halo2_zcash"]
kzg = ["halo2_kzg"]


